import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Default from "./layouts/default";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Simple Quicks",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Default>{children}</Default>
      </body>
    </html>
  );
}
